# Generated by Django 5.0.7 on 2026-06-16 13:54

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[('unpaid', '待缴费'), ('partial', '部分缴费'), ('paid', '已缴费'), ('overdue', '已逾期'), ('cancelled', '已作废')], default='unpaid', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='communities.bill'),
        ),
        migrations.AlterField(
            model_name='room',
            name='area',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='建筑面积'),
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_no', models.CharField(max_length=40, unique=True, verbose_name='分期编号')),
                ('sequence', models.PositiveIntegerField(verbose_name='期次')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='分期金额')),
                ('due_date', models.DateField(verbose_name='截止日期')),
                ('status', models.CharField(choices=[('unpaid', '待缴费'), ('paid', '已缴费'), ('overdue', '已逾期')], default='unpaid', max_length=20, verbose_name='状态')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='缴费时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='communities.bill')),
            ],
            options={
                'verbose_name': '分期记录',
                'verbose_name_plural': '分期记录',
                'ordering': ['bill', 'sequence'],
                'unique_together': {('bill', 'sequence')},
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='installment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='communities.installment'),
        ),
    ]
