# Generated by Django 5.0.7 on 2026-06-16 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_alter_bill_status_alter_payment_bill_alter_room_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='ever_overdue',
            field=models.BooleanField(default=False, verbose_name='曾逾期'),
        ),
    ]
